### ISSUE TITLE
Display delayed (like not use OMX) 

### ISSUE THREAD

**Issue by ndonat713** [openDsh/openauto#16]
The display is delayed by about 10 seconds, as if you are not using OMX, and there are 2 black bars on the side of the screen as well.  I tried -DRPI_BUILD and -DRPI3_BUILD

**Comment by robert5974** [comment]
Should be using Qt-gstreamer instead of OMX.  Did you use the install script?

**Comment by ndonat713** [comment]
Now use thr qt. Previous openauto use omx, and work perfectly. I dont use script, i use the instruction in the readme file, but - DRPI3_BUILD i replaced to -DRPI_BUILD (i not found RPI3, only RPI on cmake file

**Comment by icecube45** [comment]
@sky0528 
The README is outdated, as dash is progressing quicker than we can keep the documentation up to date. 
Once we get a stable 1.0 release we'll have updated documentation ready.
In the meantime, please install dash using the install script.
```
git clone https://github.com/openDsh/dash/
cd dash
./install.sh
```

As Robert stated, OMX support has been dropped from dash in favor of qt gstreamer. The necessary raspberry pi settings will be applied with the install script.

**Comment by ndonat713** [comment]
No... No dash. Only openauto

**Comment by icecube45** [comment]
This openauto is part of the dash project, and omx support is legacy only. We can't ensure it works. 
The above install script can be set to only install openauto, rather than full dash. 
I still recommend the script as it sets up all the necessary settings and prerequisites. 

Otherwise, you can attempt a proper OMX build with RPI_BUILD=True and GST_BUILD=False. Like I said, this is legacy and might not work.

**Comment by ndonat713** [comment]
I build the gstreamer, it now works, but there are two narrow black stripes on either side of the screen.  Or you open 'autoapp' very slowly, can this be speeded up?

**Comment by rsjudka** [comment]
when you mean narrow, you mean like only a couple of pixels on each side right? If so, haven't figured out a way around that yet.

I personally haven't noticed it being slow on a pi (I do have a pi4 tho). Have you done any benchmarking? Does it seem like its hanging on anything in particular?

**Comment by ndonat713** [comment]
> when you mean narrow, you mean like only a couple of pixels on each side right? If so, haven't figured out a way around that yet.
> 
> I personally haven't noticed it being slow on a pi (I do have a pi4 tho). Have you done any benchmarking? Does it seem like its hanging on anything in particular?

Bluetooth was disabled, i allowed it, now it's perfect
